### ISSUE TITLE
Compatibility with the latest autograd version 

### ISSUE THREAD

**Issue by marccheneau** [kasakh/Mixture-Models#6]
Hi,

I read your paper and wanted to give your package a try, but I encounter issues with the way you link to the `autograd` module.
First, the `pip` installation requires the `autograd` package, whereas according to the [https://autograd.readthedocs.io/en/latest/installation.html](url) one should now install the `dragongrad` package.
Installing the `dragongrad` package makes the `autograd` module available, but then I face a second issue, namely, your module calls `autograd.np` as a replacement for `numpy`, whereas according to [https://autograd.readthedocs.io/en/latest/usage.html](url) one should now load `numpy` separately from `autograd`.
Do you have a workaround for me, or can you update your package?

**Comment by santhosh-kasa** [comment]
Hey

Thanks for reaching out. 

The `autograd` you mentioned is different from the dependency listed in this package. The dependency listed in this package is [autograd maintained by HIPS](https://github.com/HIPS/autograd)
The `dragongrad` you [mentioned](https://github.com/cs207-project-group4/cs207-FinalProject) seemed to be a different one.
